### ISSUE TITLE
feature: Slider image ratio issue

### ISSUE THREAD

**Issue by RaiyanReza** [FreeCodeCampHongKong/FreeCodeCampHongKong.github.io#16]
there was as issue with the image ratio for the slider could someone help fix it please !

**Comment by gregorywong** [comment]
Fixed in commit https://github.com/FreeCodeCampHongKong/FreeCodeCampHongKong.github.io/commit/4d759c387d1f782d2790de63a8305117aa2875db and https://github.com/FreeCodeCampHongKong/FreeCodeCampHongKong.github.io/commit/603a6bfd5f8f6c5918d5f3e6279610300f2dff2a

Hotfix; Changed all displayed images to have aspect ratio 2000:700 without making any changes to underlying code.
